name: "Arctic Plant AGB Greenland tiles A3 B2 B3"

workflow:
  type: "shell"

input:
  params:
    - type: "dataone"
      dataset_identifier: "resource_map_doi:10.18739/A2NS0M06B"
      filename: "plant_agb_2020_*_B3.tif"
    - type: "dataone"
      dataset_identifier: "resource_map_doi:10.18739/A2NS0M06B"
      filename: "plant_agb_2020_*_A3.tif"
    - type: "dataone"
      dataset_identifier: "resource_map_doi:10.18739/A2NS0M06B"
      filename: "plant_agb_2020_*_B2.tif"

output:
  type: "temporary"
