name: "Water measurements from seal tag data"
id: "seal_tags"
input:
  url: "https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A31162eb9-7e3b-4b88-948f-f4c99f13a83f"
output:
  dataone_id: "TODO"
