name: "Water measurements from seal tag data"
# IMPORTANT: _ is not allowed in k8s object names, and we will use this string
# to create those, so we have to ban _. Only allowed chars are `-`, `.`,
# lowercase alphanumeric. Is there a pydantic validator we can use? We need to
# design a schema for meta.yaml too. That should probably live in the
# runner...?
workflow:
  type: "shell"
input:
  params:
    - value: "https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A31162eb9-7e3b-4b88-948f-f4c99f13a83f"
      type: "url"
output:
  path: "ct71_ODV_epsg3413.gpkg"

  # config
  publish:
   enabled: true
   target_dataset: "urn:uuid:1f3f702f-9594-4293-8cbd-07932e54e8ed"
   member_node: "https://test.arcticdata.io/metacat/d1/mn"
   format_id: "application/geopackage+sqlite3"
   entity_name: "CT71 Seal Tag Data (EPSG:3413)"
   entity_description: "Seal tag water measurements reprojected to EPSG:3413 polar stereographic"

  # fills in on successful publish
  dataone_id: null

