name: "Water measurements from seal tag data"
# IMPORTANT: _ is not allowed in k8s object names, and we will use this string
# to create those, so we have to ban _. Only allowed chars are `-`, `.`,
# lowercase alphanumeric. Is there a pydantic validator we can use? We need to
# design a schema for meta.yaml too. That should probably live in the
# runner...?
workflow:
  type: "shell"
input:
  params:
    - type: "dataone"
      value: "urn:uuid:1f3f702f-9594-4293-8cbd-07932e54e8ed"
      # value: "urn:uuid:31162eb9-7e3b-4b88-948f-f4c99f13a83f"
      # value: "urn:uuid:cfe3fbb2-0585-40b5-8243-8fa47fcfeb9b" # dataset identifier string
      # filename: 
      # query dataone through dataone API this would fill the url
      # "https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A31162eb9-7e3b-4b88-948f-f4c99f13a83f"
output:
  dataone_id: "TODO"
