name: "Water measurements from seal tag data"
# IMPORTANT: _ is not allowed in k8s object names, and we will use this string
# to create those, so we have to ban _. Only allowed chars are `-`, `.`,
# lowercase alphanumeric. Is there a pydantic validator we can use? We need to
# design a schema for meta.yaml too. That should probably live in the
# runner...?
workflow:
  type: "shell"
input:
  params:
    - type: "dataone"
      value:  "resource_map_urn:uuid:cfe3fbb2-0585-40b5-8243-8fa47fcfeb9b"
output:
  dataone_id: "TODO"
