name: "Ice Basins PDG"
# IMPORTANT: _ is not allowed in k8s object names, and we will use this string
# to create those, so we have to ban _. Only allowed chars are `-`, `.`,
# lowercase alphanumeric. Is there a pydantic validator we can use? We need to
# design a schema for meta.yaml too. That should probably live in the
# runner...?
id: "ice-basins"
  # TODO: figure out accessing the data differently than this: https://github.com/QGreenland-Net/argo-exploration/blob/main/data/Ice_Basins_1000.gpkg
input:
  url: "https://github.com/QGreenland-Net/argo-exploration/raw/medium-workflow/data/Ice_Basins_1000.gpkg" 
output:
  dataone_id: "TODO"
